# Generated by Django 4.2 on 2023-04-22 09:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200)),
                ('article_published', models.DateTimeField(verbose_name='date published')),
                ('article_image', models.ImageField(upload_to='images/')),
                ('article_content', tinymce.models.HTMLField()),
                ('article_slug', models.SlugField()),
            ],
        ),
    ]
